
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.table.AbstractTableModel;
import java.sql.*;
import javax.swing.JOptionPane;


public class billing_history extends javax.swing.JFrame {

    ArrayList<bill> al = new ArrayList<>();
    ArrayList<bill_details> al1 = new ArrayList<>();

    mytablemodel tm = new mytablemodel();
    mytablemodel2 tm1 = new mytablemodel2();

    public billing_history() {

        initComponents();
        getContentPane().setBackground(Color.black);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        jScrollPane2.setVisible(false);
        jLabel2.setVisible(false);
        jTable1.setModel(tm);
        jTable2.setModel(tm1);
        setTitle("Billing History");
        setSize(1500, 1000);
        setVisible(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        viewHistory();
    }

    public class mytablemodel extends AbstractTableModel {

        @Override
        public int getRowCount() {
            return al.size();
        }

        @Override
        public int getColumnCount() {
            return 6;
        }

        @Override
        public String getColumnName(int j) {
            String b[] = {"bill_id", "date time", "total price", "username", "customer no", "payment type"};
            return b[j];
        }

        @Override
        public Object getValueAt(int i, int j) {
            bill b = al.get(i);
            if (j == 0) {
                return b.bill_id;
            } else if (j == 1) {
                return b.date_time;
            } else if (j == 2) {
                return b.total_price;
            } else if (j == 3) {
                return b.username;
            } else if (j == 4) {
                return b.customer_no;
            } else {
                return b.payment_method;
            }
        }

    }

    public class mytablemodel2 extends AbstractTableModel {

        @Override
        public int getRowCount() {
            return al1.size();
        }

        @Override
        public int getColumnCount() {
            return 5;
        }

        @Override
        public String getColumnName(int j) {
            String b[] = {"billing_details_id", "billing_id", "product_name", "price", "offer price"};
            return b[j];
        }

        @Override
        public Object getValueAt(int i, int j) {
            bill_details bd = al1.get(i);
            if (j == 0) {
                return bd.bill_details_id;
            } else if (j == 1) {
                return bd.billing_id;
            } else if (j == 2) {
                return bd.product_name;
            } else if (j == 3) {
                return bd.price;
            } else {
                return bd.offerprice;
            }
        }

    }

    void viewHistory() {
        try {
            al.clear();
            ResultSet rs = DBLoader.exexuteSQL("select * from bill where username='"+global.admin_name+"' ");
            while (rs.next()) {
                int bill_id = rs.getInt("bill_id");
                String date_time = rs.getString("date_time");
                int total_price = rs.getInt("total_price");
                String username = rs.getString("username");
                String customer_no = rs.getString("customer_no");
                String payment_type = rs.getString("payment_type");
                al.add(new bill(bill_id, date_time, total_price, username, customer_no, payment_type));
            }
            tm.fireTableDataChanged();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        bg_billing_history = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 550, 510);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(580, 60, 640, 510);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BILL HISTORY");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 0, 460, 50);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BILL DETAILS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(650, 0, 440, 50);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("View Bill Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(170, 590, 190, 40);

        bg_billing_history.setIcon(new javax.swing.ImageIcon(getClass().getResource("/generate bill.jpg"))); // NOI18N
        getContentPane().add(bg_billing_history);
        bg_billing_history.setBounds(0, 0, 1500, 1000);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int i = -1;
        i = jTable1.getSelectedRow();

        if (i == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row from table");
        } else {
            jScrollPane2.setVisible(true);
            jLabel2.setVisible(true);

            int bill_id = al.get(i).bill_id;
            try {
                ResultSet rs = DBLoader.exexuteSQL("select * from bill_details where bill_id='" + bill_id + "' ");
                while(rs.next()){
                int bill_details_id = rs.getInt("bill_details_id");
                int billing_id = rs.getInt("bill_id");
                String product_name = rs.getString("product_name");
                int price = rs.getInt("price");
                int offerprice = rs.getInt("offerprice");
                al1.add(new bill_details(bill_details_id, billing_id, product_name, price, offerprice));
                }
                tm1.fireTableDataChanged();
                } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(billing_history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(billing_history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(billing_history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(billing_history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new billing_history().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_billing_history;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
