
public class categorydesign extends javax.swing.JPanel {

    /**
     * Creates new form categorydesign
     */
    public categorydesign() {
        initComponents();
        setSize(200,200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        lb1.setBackground(new java.awt.Color(0, 0, 0));
        lb1.setForeground(new java.awt.Color(255, 255, 255));
        lb1.setText("jLabel1");
        add(lb1);
        lb1.setBounds(16, 6, 170, 160);

        lb2.setBackground(new java.awt.Color(0, 0, 0));
        lb2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lb2.setForeground(new java.awt.Color(255, 255, 255));
        lb2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb2.setText("jLabel2");
        add(lb2);
        lb2.setBounds(20, 166, 160, 20);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lb1;
    public javax.swing.JLabel lb2;
    // End of variables declaration//GEN-END:variables
}
