
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;


public class settleBill extends javax.swing.JFrame {

    /**
     * Creates new form settleBill
     */
    ArrayList<cart> al;

    public settleBill(ArrayList<cart> al) {

        initComponents();
        getContentPane().setBackground(Color.black);
        this.al = al;
        cb.addItem("Online");
        cb.addItem("Cash");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setTitle("Settle Bill");
        setSize(600, 500);
        setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cb = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        bg_settleBill = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Customer Mobile No.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 130, 210, 40);

        tf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfActionPerformed(evt);
            }
        });
        getContentPane().add(tf);
        tf.setBounds(290, 130, 230, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Payment Method");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 210, 170, 50);

        cb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActionPerformed(evt);
            }
        });
        getContentPane().add(cb);
        cb.setBounds(290, 220, 170, 40);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PAYMENT INFORMATION");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 20, 380, 60);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Proceed");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 320, 130, 40);

        bg_settleBill.setBackground(new java.awt.Color(0, 0, 0));
        bg_settleBill.setForeground(new java.awt.Color(255, 255, 255));
        bg_settleBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contact number.jpg"))); // NOI18N
        getContentPane().add(bg_settleBill);
        bg_settleBill.setBounds(0, 0, 600, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        settleBill();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbActionPerformed

    void settleBill() {
        String payment_type = (String) cb.getSelectedItem();
        String customer_mobile = tf.getText();
        if (payment_type == "Select" || customer_mobile.isEmpty()) {
            JOptionPane.showMessageDialog(this, "all the field are required");
        } else if (customer_mobile.length() != 10) {
            JOptionPane.showMessageDialog(this, "Mobile Number must be of length 10");
        } else {
            try {
                long mobile_no = Long.parseLong(customer_mobile);
                ResultSet rs = DBLoader.exexuteSQL("select * from bill");
                rs.moveToInsertRow();
                rs.updateInt("total_price", global.total_amount);
                rs.updateString("username", global.admin_name);
                rs.updateLong("customer_no", mobile_no);
                rs.updateString("payment_type", payment_type);
                rs.insertRow();
                JOptionPane.showMessageDialog(this, "Inserted");
                ResultSet rs1 = DBLoader.exexuteSQL("select max(bill_id) from point_of_sale.bill;");
                int bill_id = 0;
                if (rs1.next()) {
                    bill_id = rs1.getInt("max(bill_id)");
                    JOptionPane.showMessageDialog(this, "bill_id got");
                } else {
                    JOptionPane.showMessageDialog(this, "no bill_data found");
                }
                for (int i = 0; i < al.size(); i++) {
                    ResultSet rs2 = DBLoader.exexuteSQL("select * from bill_details");
                    rs2.moveToInsertRow();
                    rs2.updateInt("bill_id", bill_id);
                    rs2.updateString("product_name", al.get(i).product_name);
                    rs2.updateInt("price", al.get(i).price);
                    rs2.updateInt("offerprice", al.get(i).offerprice);
                    rs2.insertRow();
                }
                JOptionPane.showMessageDialog(this, "Bill Procedure Done !!");
                dispose();
                //insert bill table
                //get bill id (MAX)
                //insert bill details and empty al
            } catch (Exception e) {
                e.printStackTrace();
            }
            

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(settleBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(settleBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(settleBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(settleBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new settleBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_settleBill;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    public javax.swing.JComboBox<String> cb;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JTextField tf;
    // End of variables declaration//GEN-END:variables
}
